#!/usr/bin/env python3
"""
PROTOTYPE support. Builds a throwaway two-repo demo estate in a temp directory
so the prototype can be driven over every acceptance scenario in spec 0001 §16.

    python3 make_fixture.py /tmp/estate
    python3 orbit_prototype.py orient --roots /tmp/estate

Not a test fixture. Real fixtures get harvested from the audit, per the spec.
"""
import json
import os
import subprocess
import sys

FILES = {
    "repo-one/CLAUDE.md": (
        "# repo-one\n\nAlways-on instructions for this repository.\n"
        "Estimating rules live in [docs/estimating.md](docs/estimating.md).\n"
    ),
    "repo-one/docs/CLAUDE.md": (
        "# docs scope\n\nNested surface. Applies when working under docs/.\n"
    ),
    "repo-one/docs/estimating.md": "# Estimating\n\nAnchors, precedence, figures.\n",
    "repo-one/docs/index.md": (
        "# Index\n\n"
        "- cross repo: [repo-two readme](../../repo-two/README.md)\n"
        "- missing:   [shared policy](../shared/policy.md)\n"
        "- external:  [spec](https://example.invalid/spec)\n"
    ),
    "repo-one/README.md": (
        "<!-- Generated by scripts/build-matrix.py -- DO NOT EDIT -->\n"
        "# repo-one\n\nSee [the index](docs/index.md).\n"
    ),
    "repo-one/scripts/build-matrix.py": (
        "#!/usr/bin/env python3\n"
        "# writes README.md\n"
        "open('README.md', 'w').write('generated')\n"
    ),
    "repo-one/scripts/guard.sh": "#!/bin/sh\necho '{\"decision\":\"allow\"}'\n",
    "repo-one/.claude/settings.json": json.dumps({
        "hooks": {
            "PreToolUse": [{
                "matcher": "Bash",
                "hooks": [{"type": "command", "command": "scripts/guard.sh"}],
            }],
            "SessionStart": [{
                "matcher": "*",
                "hooks": [{"type": "command", "command": "scripts/guard.sh"}],
            }],
        }
    }, indent=2) + "\n",
    "repo-one/.claude/skills/set-breakout/SKILL.md": (
        "---\nname: set-breakout\n"
        "description: Split an issued drawing set into the working sets an "
        "estimator marks up.\n---\n\n"
        "# Set breakout\n\nLong body that only loads when the skill is invoked.\n"
        + ("Procedure step.\n" * 40)
    ),
    "repo-one/.claude/agents/reviewer.md": (
        "---\nname: reviewer\ndescription: Reviews a takeoff against the spec.\n---\n\n"
        "# Reviewer\n\nBody loads only when this agent is spawned.\n"
    ),
    "repo-one/orphan-note.md": "# Note\n\nNothing in the estate points at this file.\n",
    "repo-one/shared-rule.md": "# Git rule\n\nAlways branch before committing.\n",
    "repo-two/README.md": "# repo-two\n\nBack to [repo-one](../repo-one/README.md).\n",
    "repo-two/shared-rule.md": "# Git rule\n\nAlways branch before committing.\n",
}


def main(dest):
    for rel, body in FILES.items():
        path = os.path.join(dest, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(body)
    os.chmod(os.path.join(dest, "repo-one/scripts/guard.sh"), 0o755)
    for repo in ("repo-one", "repo-two"):
        r = os.path.join(dest, repo)
        subprocess.run(["git", "init", "-q", "-b", "main", r], check=True)
        subprocess.run(["git", "-C", r, "add", "-A"], check=True)
        subprocess.run(["git", "-C", r, "-c", "user.email=f@x", "-c", "user.name=f",
                        "commit", "-qm", "fixture"], check=True)
    subprocess.run(["git", "-C", os.path.join(dest, "repo-one"),
                    "branch", "experiment"], check=True)
    print(dest)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/estate")
